// Automatically generated by AspectGo (github.com/Jakegogo/aspectgo)
// DO NOT EDIT MANUALLY

package aspect

import (
	"fmt"
	"testing"
)

func TestAsyncCall(t *testing.T) {
	obj := &Obj{}
	fmt.Println(obj.AsyncCall(1))
}
