// Code generated by github.com/ungerik/pkgreflect DO NOT EDIT.

package sexpr

import "reflect"

var Types = map[string]reflect.Type{}

var Functions = map[string]reflect.Value{
	"SetUnexportField": reflect.ValueOf(SetUnexportField),
}

var Variables = map[string]reflect.Value{}

var Consts = map[string]reflect.Value{}
