// Code generated by github.com/ungerik/pkgreflect DO NOT EDIT.

package typeassert

import "reflect"

var Types = map[string]reflect.Type{
	"S1": reflect.TypeOf((*S1)(nil)).Elem(),
}

var Functions = map[string]reflect.Value{}

var Variables = map[string]reflect.Value{}

var Consts = map[string]reflect.Value{}
