// Code generated by github.com/ungerik/pkgreflect DO NOT EDIT.

package gls

import "reflect"

var Types = map[string]reflect.Type{
	"AutoInc": reflect.TypeOf((*AutoInc)(nil)).Elem(),
	"TraceIDContext": reflect.TypeOf((*TraceIDContext)(nil)).Elem(),
}

var Functions = map[string]reflect.Value{
	"Clear": reflect.ValueOf(Clear),
	"GetContext": reflect.ValueOf(GetContext),
	"GetTraceID": reflect.ValueOf(GetTraceID),
	"NewAutoInc": reflect.ValueOf(NewAutoInc),
	"SetContext": reflect.ValueOf(SetContext),
}

var Variables = map[string]reflect.Value{
}

var Consts = map[string]reflect.Value{
	"TRACE_KEY": reflect.ValueOf(TRACE_KEY),
}

